
#define _BASE 0
#define _FN 1
#define _CONF 2
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define USB_SUSPEND_WAKEUP_DELAY 100
#define WS2812_DI_PIN D4
// The number of LEDs connected
#define LAYER_STATE_8BIT
#define NO_MUSIC_MODE
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define USB_SUSPEND_WAKEUP_DELAY 100
#define RGB_MATRIX_LEDMAPS_ENABLED
#define RGB_MATRIX_DISABLE_KEYCODES
#undef TAP_CODE_DELAY
#define TAP_CODE_DELAY 80
#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#undef LOCKING_RESYNC_ENABLE
#undef LOCKING_SUPPORT_ENABLE
#define RGB_MATRIX_DEFAULT_FLAGS LED_FLAG_ALL


